//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace SalesforceProfileRefactor { // Namespace needed for Partial Class. You will need to add again if you regenerate this Profile class.

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.sforce.com/2006/04/metadata")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://soap.sforce.com/2006/04/metadata", IsNullable=false)]
public partial class Profile {
    
    private ProfileApplicationVisibilities[] applicationVisibilitiesField;
    
    private ProfileCategoryGroupVisibilities[] categoryGroupVisibilitiesField;
    
    private ProfileClassAccesses[] classAccessesField;
    
    private bool customField;
    
    private ProfileCustomMetadataTypeAccesses[] customMetadataTypeAccessesField;
    
    private ProfileCustomPermissions[] customPermissionsField;
    
    private ProfileFieldPermissions[] fieldPermissionsField;
    
    private ProfileLayoutAssignments[] layoutAssignmentsField;
    
    private ProfileLoginIpRanges[] loginIpRangesField;
    
    private ProfileObjectPermissions[] objectPermissionsField;
    
    private ProfilePageAccesses[] pageAccessesField;
    
    private ProfileRecordTypeVisibilities[] recordTypeVisibilitiesField;
    
    private ProfileTabVisibilities[] tabVisibilitiesField;
    
    private string userLicenseField;
    
    private ProfileUserPermissions[] userPermissionsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("applicationVisibilities")]
    public ProfileApplicationVisibilities[] applicationVisibilities {
        get {
            return this.applicationVisibilitiesField;
        }
        set {
            this.applicationVisibilitiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("categoryGroupVisibilities")]
    public ProfileCategoryGroupVisibilities[] categoryGroupVisibilities {
        get {
            return this.categoryGroupVisibilitiesField;
        }
        set {
            this.categoryGroupVisibilitiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("classAccesses")]
    public ProfileClassAccesses[] classAccesses {
        get {
            return this.classAccessesField;
        }
        set {
            this.classAccessesField = value;
        }
    }
    
    /// <remarks/>
    public bool custom {
        get {
            return this.customField;
        }
        set {
            this.customField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("customMetadataTypeAccesses")]
    public ProfileCustomMetadataTypeAccesses[] customMetadataTypeAccesses {
        get {
            return this.customMetadataTypeAccessesField;
        }
        set {
            this.customMetadataTypeAccessesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("customPermissions")]
    public ProfileCustomPermissions[] customPermissions {
        get {
            return this.customPermissionsField;
        }
        set {
            this.customPermissionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("fieldPermissions")]
    public ProfileFieldPermissions[] fieldPermissions {
        get {
            return this.fieldPermissionsField;
        }
        set {
            this.fieldPermissionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("layoutAssignments")]
    public ProfileLayoutAssignments[] layoutAssignments {
        get {
            return this.layoutAssignmentsField;
        }
        set {
            this.layoutAssignmentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("loginIpRanges")]
    public ProfileLoginIpRanges[] loginIpRanges {
        get {
            return this.loginIpRangesField;
        }
        set {
            this.loginIpRangesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("objectPermissions")]
    public ProfileObjectPermissions[] objectPermissions {
        get {
            return this.objectPermissionsField;
        }
        set {
            this.objectPermissionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pageAccesses")]
    public ProfilePageAccesses[] pageAccesses {
        get {
            return this.pageAccessesField;
        }
        set {
            this.pageAccessesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("recordTypeVisibilities")]
    public ProfileRecordTypeVisibilities[] recordTypeVisibilities {
        get {
            return this.recordTypeVisibilitiesField;
        }
        set {
            this.recordTypeVisibilitiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tabVisibilities")]
    public ProfileTabVisibilities[] tabVisibilities {
        get {
            return this.tabVisibilitiesField;
        }
        set {
            this.tabVisibilitiesField = value;
        }
    }
    
    /// <remarks/>
    public string userLicense {
        get {
            return this.userLicenseField;
        }
        set {
            this.userLicenseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("userPermissions")]
    public ProfileUserPermissions[] userPermissions {
        get {
            return this.userPermissionsField;
        }
        set {
            this.userPermissionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.sforce.com/2006/04/metadata")]
public partial class ProfileApplicationVisibilities {
    
    private string applicationField;
    
    private bool defaultField;
    
    private bool visibleField;
    
    /// <remarks/>
    public string application {
        get {
            return this.applicationField;
        }
        set {
            this.applicationField = value;
        }
    }
    
    /// <remarks/>
    public bool @default {
        get {
            return this.defaultField;
        }
        set {
            this.defaultField = value;
        }
    }
    
    /// <remarks/>
    public bool visible {
        get {
            return this.visibleField;
        }
        set {
            this.visibleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.sforce.com/2006/04/metadata")]
public partial class ProfileCategoryGroupVisibilities {
    
    private string[] dataCategoriesField;
    
    private string dataCategoryGroupField;
    
    private string visibilityField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dataCategories")]
    public string[] dataCategories {
        get {
            return this.dataCategoriesField;
        }
        set {
            this.dataCategoriesField = value;
        }
    }
    
    /// <remarks/>
    public string dataCategoryGroup {
        get {
            return this.dataCategoryGroupField;
        }
        set {
            this.dataCategoryGroupField = value;
        }
    }
    
    /// <remarks/>
    public string visibility {
        get {
            return this.visibilityField;
        }
        set {
            this.visibilityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.sforce.com/2006/04/metadata")]
public partial class ProfileClassAccesses {
    
    private string apexClassField;
    
    private bool enabledField;
    
    /// <remarks/>
    public string apexClass {
        get {
            return this.apexClassField;
        }
        set {
            this.apexClassField = value;
        }
    }
    
    /// <remarks/>
    public bool enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.sforce.com/2006/04/metadata")]
public partial class ProfileCustomMetadataTypeAccesses {
    
    private bool enabledField;
    
    private string nameField;
    
    /// <remarks/>
    public bool enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.sforce.com/2006/04/metadata")]
public partial class ProfileCustomPermissions {
    
    private bool enabledField;
    
    private string nameField;
    
    /// <remarks/>
    public bool enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.sforce.com/2006/04/metadata")]
public partial class ProfileFieldPermissions {
    
    private bool editableField;
    
    private string fieldField;
    
    private bool readableField;
    
    /// <remarks/>
    public bool editable {
        get {
            return this.editableField;
        }
        set {
            this.editableField = value;
        }
    }
    
    /// <remarks/>
    public string field {
        get {
            return this.fieldField;
        }
        set {
            this.fieldField = value;
        }
    }
    
    /// <remarks/>
    public bool readable {
        get {
            return this.readableField;
        }
        set {
            this.readableField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.sforce.com/2006/04/metadata")]
public partial class ProfileLayoutAssignments {
    
    private string layoutField;
    
    private string recordTypeField;
    
    /// <remarks/>
    public string layout {
        get {
            return this.layoutField;
        }
        set {
            this.layoutField = value;
        }
    }
    
    /// <remarks/>
    public string recordType {
        get {
            return this.recordTypeField;
        }
        set {
            this.recordTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.sforce.com/2006/04/metadata")]
public partial class ProfileLoginIpRanges {
    
    private string endAddressField;
    
    private string startAddressField;
    
    /// <remarks/>
    public string endAddress {
        get {
            return this.endAddressField;
        }
        set {
            this.endAddressField = value;
        }
    }
    
    /// <remarks/>
    public string startAddress {
        get {
            return this.startAddressField;
        }
        set {
            this.startAddressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.sforce.com/2006/04/metadata")]
public partial class ProfileObjectPermissions {
    
    private bool allowCreateField;
    
    private bool allowDeleteField;
    
    private bool allowEditField;
    
    private bool allowReadField;
    
    private bool modifyAllRecordsField;
    
    private string objectField;
    
    private bool viewAllRecordsField;
    
    /// <remarks/>
    public bool allowCreate {
        get {
            return this.allowCreateField;
        }
        set {
            this.allowCreateField = value;
        }
    }
    
    /// <remarks/>
    public bool allowDelete {
        get {
            return this.allowDeleteField;
        }
        set {
            this.allowDeleteField = value;
        }
    }
    
    /// <remarks/>
    public bool allowEdit {
        get {
            return this.allowEditField;
        }
        set {
            this.allowEditField = value;
        }
    }
    
    /// <remarks/>
    public bool allowRead {
        get {
            return this.allowReadField;
        }
        set {
            this.allowReadField = value;
        }
    }
    
    /// <remarks/>
    public bool modifyAllRecords {
        get {
            return this.modifyAllRecordsField;
        }
        set {
            this.modifyAllRecordsField = value;
        }
    }
    
    /// <remarks/>
    public string @object {
        get {
            return this.objectField;
        }
        set {
            this.objectField = value;
        }
    }
    
    /// <remarks/>
    public bool viewAllRecords {
        get {
            return this.viewAllRecordsField;
        }
        set {
            this.viewAllRecordsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.sforce.com/2006/04/metadata")]
public partial class ProfilePageAccesses {
    
    private string apexPageField;
    
    private bool enabledField;
    
    /// <remarks/>
    public string apexPage {
        get {
            return this.apexPageField;
        }
        set {
            this.apexPageField = value;
        }
    }
    
    /// <remarks/>
    public bool enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.sforce.com/2006/04/metadata")]
public partial class ProfileRecordTypeVisibilities {
    
    private bool defaultField;
    
    private bool personAccountDefaultField;
    
    private bool personAccountDefaultFieldSpecified;
    
    private string recordTypeField;
    
    private bool visibleField;
    
    /// <remarks/>
    public bool @default {
        get {
            return this.defaultField;
        }
        set {
            this.defaultField = value;
        }
    }
    
    /// <remarks/>
    public bool personAccountDefault {
        get {
            return this.personAccountDefaultField;
        }
        set {
            this.personAccountDefaultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool personAccountDefaultSpecified {
        get {
            return this.personAccountDefaultFieldSpecified;
        }
        set {
            this.personAccountDefaultFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string recordType {
        get {
            return this.recordTypeField;
        }
        set {
            this.recordTypeField = value;
        }
    }
    
    /// <remarks/>
    public bool visible {
        get {
            return this.visibleField;
        }
        set {
            this.visibleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.sforce.com/2006/04/metadata")]
public partial class ProfileTabVisibilities {
    
    private string tabField;
    
    private string visibilityField;
    
    /// <remarks/>
    public string tab {
        get {
            return this.tabField;
        }
        set {
            this.tabField = value;
        }
    }
    
    /// <remarks/>
    public string visibility {
        get {
            return this.visibilityField;
        }
        set {
            this.visibilityField = value;
        }
    }
}

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://soap.sforce.com/2006/04/metadata")]
    public partial class ProfileUserPermissions
    {

        private bool enabledField;

        private string nameField;

        /// <remarks/>
        public bool enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
}
